fpillet/NSLogger

Desktop Viewer/Classes/LoggerWindowController.m
When a marker is added via `LogMarkerTo` and the text is an empty string, mark.message is nil and makes NSMenuItem initialization crash.
=> Fix crash on empty marker

Desktop Viewer/Classes/LoggerMessage.m
Using the sprintf function with a %04x format does not limit string to 4 characters. Displaying more than 64 KB of raw data would lead to a buffer overflow and a crash.
=> Fix crash when displaying more than 64 KB of raw data

Client Logger/iOS/LoggerClient.h
When change Xcode buildingsetting `C++ Language Dialect` and `C++ Standard Library` when integrate with VLC.
=> Bugfix for change Xcode buildingsetting

README.markdown
LoggerStart(LoggerGetDefaultLogger()); is the only way I've gotten NSLogger to work properly.
Simply adding LoggerStartForBuildUser(); doesn't seem to work.
=> Fixed issue in NSLogger documentation.

Desktop Viewer/Classes/LoggerMessage.m, Desktop Viewer/Classes/LoggerMessageCell.m
#169 broke a great feature: setting a color per level. This commit restores this feature. It is now possible to define the following advanced colors:
Comment  | Regular Expression | Color
-------- | ------------------ | -----
Warnings | level=1            | bold orange
Errors   | level=0            | bold red
=> Enable Advanced Colors per level

Client Logger/iOS/LoggerClient.m, Desktop Viewer/Classes/LoggerConnection.m, Desktop Viewer/Classes/LoggerIPConnection.m, Desktop Viewer/Classes/LoggerTCPTransport.m, Desktop Viewer/Classes/LoggerTransport.m
This pull requests implements peer-to-peer browsing so that you can use NSLogger between a client and the desktop viewer even if they are not both connected to the same Wi-Fi network.
As stated in 8f4f668b297620ec304d7c2b2f6e2118c9d46393:
> The only way to get peer-to-peer browsing without undocumented API is with the NSNetServiceBrowser class. This would require a big rewrite of LoggerClient.m and make `ALLOW_COCOA_USE` pretty much mandatory.
@fpillet What are your thoughts about using an undocumented API vs rewriting LoggerClient.m with NSNetServiceBrowser and dropping ALLOW_COCOA_USE?
=> Peer-to-peer browsing

NSLogger.xcodeproj/project.pbxproj
Commit 4dff843ab7c8a1bafb045d384cc4e523b0902011 changed paths but forgot to update them in the NSLogger Xcode project file.
Note that this is required for Carthage integration to work.
I think this should warrant a new 1.8.1 release.
=> Fix compilation of NSLogger.framework

Client/iOS/LoggerClient.h, Client/iOS/LoggerClient.m, Client/iOS/NSLogger.swift, NSLogger.podspec, README.markdown
List of features / changes
- Added _fast C functions to have a straight logging path when logging from swift 
- no formatting with vaargs
- not using String -> CString -> UTF8String transforms
- using NSInteger function in order to use native Swift Ints
- Provide nullability annotations to have clean swift interfaces
- Providing a wrapper using swift3+ guidelines: 
- `camelCase` members instead of `UpperCamelCase`
- Everything wrapped in a single class instead of top-level functions
=> Swiftier NSLogger

Desktop/Classes/LoggerWindowController.h, Desktop/Classes/LoggerWindowController.m
Using the Option key, multiple tags can now be selected to filter the
current view.
Selecting a single tag also reset to All Tags now.
=> Add support for multiple tags selection

Client/iOS/NSLogger.swift
This `const` is no longer is available but is exposed as an enum.
I think this is a regression in swift 3 in Xcode 9 because this used to compile in Xcode 8. The enum reports being available since 10.12. I'm not sure what to do for earlier os's.
=> Fix Compiling under Xcode 9- use the newer style filetype enum

Client/iOS/NSLogger.swift, Client/iOS/NSLoggerSwift.h, NSLogger.xcodeproj/project.pbxproj, NSLogger.xcodeproj/xcshareddata/xcschemes/NSLoggerSwift.xcscheme
Whats here:
* `NSLoggerSwift` is now its own full fledged Product (`NSLogger` as a linked dependency) With its own Product Name
* `NSLoggerSwift` no longer builds `NSLogger` files.
* Now when the project is built users have a choice between NSLogger and/or NSLoggerSwift products.
Why:
* Carthage builds could (and did) sometimes build NSLoggerSwift over the top of NSLogger because they shared the same product name
* Closes https://github.com/fpillet/NSLogger/issues/234
=> Fix carthage inconsistency

Client/iOS/LoggerClient.m
Converted single line statements with commas to multi-line with semi-colons. This stops the warning "Possible misuse of comma operator here" that I've been encountering in Xcode 9.
=> Remove "Possible misuse of comma operator here" warnings in Xcode 9

iPad Viewer/ViewController/MessageViewController/LoggerMessageViewController.xib, iPad Viewer/iPad Viewer.xcodeproj/project.pbxproj, iPad Viewer/iPad Viewer/iPad Viewer-Info.plist
1. Fixed the following compile errors:
- LoggerMessageViewController.xib: error: Illegal Configuration: Compiling IB documents for earlier than iOS 7 is no longer supported.
- LoggerCommon.h file not found.
2. Update top constraint of table view from 0 to 20 so that the status bar doesn’t cover the connected device info on top.
=> Fix Compiling errors under Xcode 9 and update top constraint of messaging controller

Desktop/Classes/LoggerNativeMessage.m
Values being sent from a 64 bits client were incorrectly read as 32 bits resulting in all levels being displayed as errors.
=> Fix parsing 64 bits encoded level

NSLogger.xcodeproj/project.pbxproj
When using the NSLoggerSwift framework within my project (built with Carthage) together with the NSLogger framework (since NSLoggerSwift needs it) I got the following error when building and running my app:
"This application or a bundle it contains has the same bundle identifier as this application or another bundle that it contains. Bundle identifiers must be unique."
This was because the bundle identifier for both the NSLogger and NSLoggerSwift targets were identical, this pull request fixes that.
=> Changes bundle identifier for NSLoggerSwift target

Client/iOS/NSLogger.swift, NSLogger.xcodeproj/project.pbxproj
Fixes `'PNG' has been renamed to 'png'` compiling under newer versions of Xcode for a macOS target..
=> Support deprecation of swift 3 compatibility

README.markdown
There is no repository `fpillet/NSLoggerSwift`
This fixes #264
=> Fix Carthage installation instructions

Desktop/Classes/LoggerConnection.m
When the code was converted from MRC to ARC, the keys that were used in `initWithCoder` from `LoggerConnection` have changed. That was causing older `.nsloggerdata` exported by older NSLogger versions to not be compatible with the newer version.
The fix is to fallback on older keys if the new keys return `nil`.
=> Fix for file compatibility issue caused by migration to ARC.

Desktop/Classes/LoggerTransport.m
This happens in our project because the first ClientInfo message received
only contains the application name and version, but not the OS details.
Afterwards a second ClientInfo is received with the full metadata set,
but by that time the connection has already been attached to a new
window.
I'm not sure if this is something we could fix in our project by
initializing NSLogger differently.
=> NSLoggerViewer: prevent new connections from creating multiple windows

Desktop/Classes/LoggerDocumentController.h, Desktop/Classes/LoggerSplitView.h, Desktop/Classes/LoggerStatusWindowController.h, Desktop/Classes/LoggerTCPConnection.m, Desktop/Classes/LoggerTableView.h, Desktop/Classes/LoggerTransportStatusCell.h, Desktop/Classes/ValueTransformers.h
Even if the compiler figures out these missing imports when building with Xcode, other tools like Bazel produce errors.
=> Add missing imports for AppKit or Foundation in several header files.
